name: Bug Report
description: File a bug report
labels: ["🐞 bug", "triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: Issue description
      description: What went wrong?

  - type: textarea
    id: zinit-config
    validations:
      required: true
    attributes:
      label: zinit config
      description: The ices you used
      placeholder: |
        ```zsh
        zinit \
          null \
          atclone'true' \
          for zdharma_continuum/null
        ```

  - type: input
    id: zsh-version
    validations:
      required: true
    attributes:
      label: ZSH Version (`$ZSH_VERSION`)
      description: ZSH version you're currently using
      placeholder: 5.8
