name: Build containers
on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        zsh_version:
          - 5.1.1
          - 5.2.4
          - 5.3.1
          - 5.4.2
          - 5.5.1
          - 5.6.2
          - 5.7.1
          - 5.8
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
          use: true

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Alpine containers
      #   run: |
      #     ./ci/docker/build.sh alpine latest ${{ matrix.zsh_version }}
      #     docker push ghcr.io/${GITHUB_REPOSITORY}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./ci/docker/Dockerfile.alpine
          build-args: |
            VERSION=latest
            ZINIT_ZSH_VERSION=${{ matrix.zsh_version }}-tcsetpgrp
          tags: ghcr.io/${{ github.repository }}:zsh-${{ matrix.zsh_version }}-latest
          platforms: linux/amd64,linux/arm64/v8
          cache-from: type=gha
          cache-to: type=gha,mode=max
