name: zshelldoc
on: [push]
jobs:
  make-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Install zshelldoc
        run: |
          sudo apt-get install -y zsh
          git clone https://github.com/zdharma-continuum/zshelldoc.git /tmp/zsd.git
          cd /tmp/zsd.git
          sudo make install
          zsd --help

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: make doc
        run: |
          make doc

      - name: Check if docs are up to date
        run: |
          git --no-pager diff

          if ! git --no-pager diff --quiet
          then
            echo "The docs in the repo are not up to date" >&2
            exit 1
          fi
