name: zshelldoc
on: [push]
jobs:
  make-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Install zshelldoc
        run: |
          sudo apt-get install -y zsh
          git clone https://github.com/zdharma-continuum/zshelldoc.git
          cd zshelldoc
          sudo make install
          zsd --help

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: make doc
        run: |
          make doc
