name: tests
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testcase:
          - test
          - testB
          - testC
          - testD
          - testE
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Check out tests branch
        run: |
          git fetch --depth=1 origin tests:tests
          git worktree add test tests

      - name: Install zsh
        run: |
          sudo apt install -y zsh

      - name: make
        run: |
          make
          make -C test ${{ matrix.testcase }} VERBOSE=1
